@startuml

package sample <<Folder>>{
package nodes <<Folder>>{
class Begin
class Operation
class Solution
}
package observers <<Folder>>{
class MovingObserver extends Observer
class PickingObserver extends Observer
class AimingObserver extends Observer
abstract class Observer
}
class Controller implements javafx.fxml.Initializable
class Main implements javafx.application.Application
class Subject
}

@enduml